export enum CardType {
  LAND = 'LAND',
  INSTANT = 'INSTANT',
  SORCERY = 'SORCERY',
  CREATURE = 'CREATURE',
  ENCHANTMENT = 'ENCHANTMENT',
  PLANESWALKER = 'PLANESWALKER',
  BATTLE = 'BATTLE',
  ARTIFACT = 'ARTIFACT'
}
